#!/bin/bash
bold=`echo -en "\e[1m"`
underline=`echo -en "\e[4m"`
dim=`echo -en "\e[2m"`
strickthrough=`echo -en "\e[9m"`
blink=`echo -en "\e[5m"`
reverse=`echo -en "\e[7m"`
hidden=`echo -en "\e[8m"`
normal=`echo -en "\e[0m"`
black=`echo -en "\e[30m"`
red=`echo -en "\e[31m"`
green=`echo -en "\e[32m"`
orange=`echo -en "\e[33m"`
blue=`echo -en "\e[34m"`
purple=`echo -en "\e[35m"`
aqua=`echo -en "\e[36m"`
gray=`echo -en "\e[37m"`
darkgray=`echo -en "\e[90m"`
lightred=`echo -en "\e[91m"`
lightgreen=`echo -en "\e[92m"`
lightyellow=`echo -en "\e[93m"`
lightblue=`echo -en "\e[94m"`
lightpurple=`echo -en "\e[95m"`
lightaqua=`echo -en "\e[96m"`
white=`echo -en "\e[97m"`
default=`echo -en "\e[39m"`
BLACK=`echo -en "\e[40m"`
RED=`echo -en "\e[41m"`
GREEN=`echo -en "\e[42m"`
ORANGE=`echo -en "\e[43m"`
BLUE=`echo -en "\e[44m"`
PURPLE=`echo -en "\e[45m"`
AQUA=`echo -en "\e[46m"`
GRAY=`echo -en "\e[47m"`
DARKGRAY=`echo -en "\e[100m"`
LIGHTRED=`echo -en "\e[101m"`
LIGHTGREEN=`echo -en "\e[102m"`
LIGHTYELLOW=`echo -en "\e[103m"`
LIGHTBLUE=`echo -en "\e[104m"`
LIGHTPURPLE=`echo -en "\e[105m"`
LIGHTAQUA=`echo -en "\e[106m"`
WHITE=`echo -en "\e[107m"`
DEFAULT=`echo -en "\e[49m"`
clear
echo "${bold}${underline}Manjaro - Installation and Configuration Script$normal"
## update and install stuff ####################################################
echo -n "${green}update and install software (y/n)? $normal"
read answer
if [ "$answer" != "${answer#[Yy]}" ] ;then
    sudo pacman -Syu
    sudo pacman -S yay
    yay -S keepass thunderbird obs-studio gimp libreoffice-fresh gufw steam krita blender atom discord
fi

## Install QEMU/KVM ############################################################
echo -n "${green}Install QEMU/KVM(y/n)? $normal"
read answer
if [ "$answer" != "${answer#[Yy]}" ] ;then
  if [[ $(egrep -c '(vmx|svm)' /proc/cpuinfo) > 0 ]];then
    echo "kvm supported and enabled in bios"
    #install virtual environment
    yay -S virt-manager qemu vde2 ebtables dnsmasq bridge-utils openbsd-netcat
    sudo gpasswd -a master kvm
    sudo systemctl enable libvirtd.service
    sudo systemctl start libvirtd.service
  else
    echo "${red}kvm not supported or not enabled in bios$normal"
  fi
fi

## Create network bridge for QEMU£/KVM #########################################
echo -n "${green}create network bridge for QEMU/KVM(y/n)? $normal"
read answer
if [ "$answer" != "${answer#[Yy]}" ] ;then
  #network bridge
  sudo brctl addbr br0
  sudo ip link set enp4s0 down
  sudo ip link set enp4s0 up
  sudo brctl addif br0 enp4s0
  sudo dhclient br0
fi
